[package]
name = "ruffle-android"
version = "0.1.0"
authors = ["TÖRÖK Attila <torokati44@gmail.com>"]
edition = "2018"
resolver = "2"

[lib]
crate-type = ["lib", "cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = "0.12.0"
# we need 0.27.0 due to oboe in cpal (ndk-glue 0.6 everywhere)
winit = { git = "https://github.com/rust-windowing/winit.git", rev = "ab1f63696047ee54f119455d3cae6e7b03aba0fb" }
#winit = {path = "../../winit" }
ndk-glue = { version = "0.6.1", features = ["logger"] }
async-executor = "1.0"
pollster = "0.2"
log = "0.4"
android_logger = "*"


#ruffle_core = { path = "../../ruffle/core", features = [ "minimp3", "h263", "vp6", "screenvideo", "lzma" ] }
#ruffle_render_wgpu = { path = "../../ruffle/render/wgpu" }

ruffle_core = { git = "https://github.com/ruffle-rs/ruffle.git", branch = "master", features = [ "minimp3", "h263", "vp6", "screenvideo", "lzma" ] }
ruffle_render_wgpu = { git = "https://github.com/ruffle-rs/ruffle.git", branch = "master" }

jni = "0.19.0"
ndk-context = "0.1.0"


cpal = "0.13.5"

[package.metadata.android]
build_targets = [ "aarch64-linux-android", "armv7-linux-androideabi" ]
target_sdk_version = 29
min_sdk_version = 23

[package.metadata.android.signing.release]
path = "debug.keystore"
keystore_password = "android"
