name: Validate Fastlane metadata

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    paths:
      - 'fastlane/**'
  push:
    branches: [ main ]
    paths:
      - 'fastlane/**'

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Validate Fastlane Supply Metadata
        uses: ashutoshgngwr/validate-fastlane-supply-metadata@v2
